version: '3'

services:
  docker-base-image:
    image: springcloud/openjdk:latest

  chaoshub:
    image: chaostoolkit/chaoshub:0.1.2
    container_name: chaoshub
    ports:
    - "8888:8080"
    tty: true
    depends_on:
      - docker-base-image

  api-gateway:
    container_name: api-gateway
    image: arau/gateway
    # need NET_ADMIN to run chaos linux experiments
    cap_add:
     - NET_ADMIN
    ports:
    - "8080:8070"
    volumes:
      - ./chaos-scripts:/var/chaosscripts
    depends_on:
      - docker-base-image

  fashion:
    container_name: fashion-bestseller
    image: arau/fashion-bestseller
    # need NET_ADMIN to run chaos linux experiments
    cap_add:
     - NET_ADMIN
    ports:
    - "8082:8082"
    volumes:
      - ./chaos-scripts:/var/chaosscripts
    depends_on:
      - docker-base-image

  toys:
    image: arau/toys-bestseller
    container_name: toys
    # need NET_ADMIN to run chaos linux experiments
    cap_add:
      - NET_ADMIN
    ports:
    - "8081:8081"
    volumes:
      - ./chaos-scripts:/var/chaosscripts
    depends_on:
      - docker-base-image

  hot-deals:
    image: arau/hot-deals
    container_name: hot-deals
    # need NET_ADMIN to run chaos linux experiments
    cap_add:
      - NET_ADMIN
    ports:
    - "8083:8083"
    volumes:
      - ./chaos-scripts:/var/chaosscripts
    depends_on:
      - docker-base-image

  eureka-server:
    image: springcloud/eureka
    container_name: eureka-server
    # need NET_ADMIN to run chaos linux experiments
    cap_add:
    - NET_ADMIN
    ports:
    - "8761:8761"
    volumes:
    - ./chaos-scripts:/var/chaosscripts
    depends_on:
    - docker-base-image