apiVersion: v1
kind: Service
metadata:
  name: hystrix-dashboard

spec:
  selector:
    app: "hystrix-dashboard"
    version: "v1"
  ports:
    - name: hdashboard
      port: 8080
      protocol: TCP
  type: "NodePort"