spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
eureka:
  client:
    enabled: false
dekorate:
  kubernetes:
    serviceType: "NodePort"
    envVars:
      - name: "SPRING_PROFILES_ACTIVE"
        value: "kubernetes"
    ports:
      - name: "http80"
        containerPort: 80
        hostPort: 8082
    livenessProbe:
      tcpSocketAction: "localhost:8082"